import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateResumePDF = (profile) => {
  const { user, skills, projects, stats, activity_streak } = profile;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = margin;

  doc.setFillColor(30, 58, 138);
  doc.rect(0, 0, pageWidth, 45, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(user.name, margin, 25);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  const roleText = user.role.charAt(0).toUpperCase() + user.role.slice(1);
  doc.text(`${roleText} • Joined ${new Date(user.join_date).toLocaleDateString("en-US", { month: "long", year: "numeric" })}`, margin, 35);

  if (activity_streak > 0) {
    doc.text(`${activity_streak} day streak!`, margin + 100, 35);
  }

  yPos = 55;

  doc.setTextColor(30, 58, 138);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Skills Overview", margin, yPos);
  yPos += 8;

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  if (skills.length > 0) {
    const skillData = skills.map((skill) => [
      skill.skill_name,
      skill.total_weight.toString(),
      skill.source_breakdown?.project || 0,
      skill.source_breakdown?.update || 0,
      skill.source_breakdown?.mentorship || 0,
      new Date(skill.last_practiced).toLocaleDateString(),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Skill", "Points", "Projects", "Updates", "Mentorship", "Last Practiced"]],
      body: skillData,
      margin: { left: margin, right: margin },
      headStyles: { fillColor: [30, 58, 138], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
    });

    yPos = doc.lastAutoTable.finalY + 15;
  } else {
    doc.text("No skills recorded yet.", margin, yPos + 5);
    yPos += 15;
  }

  if (pageWidth - yPos < 60) {
    doc.addPage();
    yPos = margin;
  }

  doc.setTextColor(30, 58, 138);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Projects", margin, yPos);
  yPos += 8;

  if (projects.length > 0) {
    const projectData = projects.slice(0, 10).map((project) => [
      project.title,
      project.status.charAt(0).toUpperCase() + project.status.slice(1),
      project.team_size.toString(),
      project.skill_count.toString(),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Project", "Status", "Team Size", "Skills"]],
      body: projectData,
      margin: { left: margin, right: margin },
      headStyles: { fillColor: [30, 58, 138], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
    });

    yPos = doc.lastAutoTable.finalY + 15;
  } else {
    doc.text("No projects yet.", margin, yPos + 5);
    yPos += 15;
  }

  if (pageWidth - yPos < 50) {
    doc.addPage();
    yPos = margin;
  }

  doc.setTextColor(30, 58, 138);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Statistics", margin, yPos);
  yPos += 10;

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const statsData = [
    ["Total Skills", stats.total_skills?.toString() || "0"],
    ["Growth Points", stats.total_weight?.toString() || "0"],
    ["Projects", stats.project_count?.toString() || "0"],
    ["Progress Updates", stats.update_count?.toString() || "0"],
    ["Mentorship Sessions", stats.mentorship_count?.toString() || "0"],
    ["Days Active", stats.days_active?.toString() || "0"],
  ];

  autoTable(doc, {
    startY: yPos,
    body: statsData,
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 50 } },
    tableWidth: 80,
    theme: "grid",
  });

  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by SyncUp • ${new Date().toLocaleDateString()} • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  const fileName = `${user.name.replace(/\s+/g, "_")}_Resume_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);

  return fileName;
};
